### ISSUE TITLE
Add Action Option for jump to url, across Windows

### ISSUE THREAD

**Issue by AH-Hammi** [onozaty/chrome-shortcutkey2url#16]
When selecting jump to url and the URL is currently open in a separate window, it opens a new tab, but the plugin should jump to that window instead

**Comment by onozaty** [comment]
Thanks for the suggestion.
I will work on implementing it soon.

**Comment by AH-Hammi** [comment]
Maybe use a combination of
https://developer.chrome.com/docs/extensions/reference/windows/#method-getAll

And
https://developer.chrome.com/docs/extensions/reference/windows/#type-Window
then retrieve the tabs from the windows

**Comment by onozaty** [comment]
Released at v1.6.0
