### ISSUE TITLE
I'm trying to js script but it does not seem to work

### ISSUE THREAD

**Issue by ondrobaco** [onozaty/chrome-shortcutkey2url#17]
Hi, thanks for a great extension. 
I'm trying putting the following script under a short cut with the extension but it does not seem to execute.
https://gist.github.com/alangrainger/ef52d535f7b1cc4c0c1b23da4e91806d
It works fine when the script is used in bookmark. 
I tried to put the code under script as well as url, but none of the options work.

Would you know where could be the problem?

**Comment by onozaty** [comment]
Hi @ondrobaco 

It seems to be because `navigator.clipboard.writeText` is not working in the extension.
This seems to be a Chrome issue.

* https://stackoverflow.com/questions/62270880/document-not-focused-error-when-writing-to-clipboard-using-clipboard-api-in-chro
* https://bugs.chromium.org/p/chromium/issues/detail?id=874848

As an alternative, i have rewritten the script with reference to the following.

* https://stackoverflow.com/questions/3436102/copy-to-clipboard-in-chrome-extension

```javascript
function copyTextToClipboard(text) {
  //Create a textbox field where we can insert text to. 
  var copyFrom = document.createElement("textarea");

  //Set the text content to be the text you wished to copy.
  copyFrom.textContent = text;

  //Append the textbox field into the body as a child. 
  //"execCommand()" only works when there exists selected text, and the text is inside 
  //document.body (meaning the text is part of a valid rendered HTML element).
  document.body.appendChild(copyFrom);

  //Select all the text!
  copyFrom.select();

  //Execute command
  document.execCommand('copy');

  //(Optional) De-select the text using blur(). 
  copyFrom.blur();

  //Remove the textbox field from the document.body, so no other JavaScript nor 
  //other elements can get access to this.
  document.body.removeChild(copyFrom);
}

messageId = document.querySelector('div[data-legacy-message-id]').getAttribute('data-legacy-message-id');
user = location.pathname.match(/\/u\/(\d)/)[1];
copyTextToClipboard('https://mail.google.com/mail/u/' + user + '/#inbox/' + messageId);
```

It is working fine at hand.
Could you please give it a try?

Thanks.

**Comment by ondrobaco** [comment]
Thank you, it works! Forever grateful :)!

**Comment by onozaty** [comment]
You're welcome!
If you would like, I would be happy to give you a Star on GitHub or a review in the Chrome web store 😉 

Thanks.

**Comment by ondrobaco** [comment]
Hi onozaty, 
There were some changes in how how the scripts work. I'm trying to get the code working again it is an immensely useful piece of code for me. I followed the "how to specify script" mini tutorial that you have on the page but no success. Would you be so kind and help me with the code to put into user-scripts.js to make the gmail link copy work again? thank you kindly

**Comment by onozaty** [comment]
I will send you a set of files that I have verified to work.
Please unzip and load this.

- [src.zip](https://github.com/user-attachments/files/15985847/src.zip)

`clipboardWrite` is added to the `manifest.json` permissions.
The script uses `navigator.clipboard.writeText`.

Thanks.

**Comment by ondrobaco** [comment]
hey Onazaty,
thank you for your help.
However, it still does not work.
I copied the whole src over the existing files in the extension folder.
I also enabled developer mode on the extension page of the browser.
It says the extension may have been corrupted and when I click Repair,
it installs the extension from the webstore.
[image: image.png]

**Comment by onozaty** [comment]
Instead of overwriting the extensions folder, could you please load the folder where you extracted the src.zip with Load Unpacked Extension?

**Comment by ondrobaco** [comment]
I just did it. Works beautifully!
Thank you so much.
Can I do anything for you?
Leave a review for something etc?

**Comment by onozaty** [comment]
If you haven't written a review on the Chrome Web Store, I would appreciate it if you would.

Thanks.
