### ISSUE TITLE
the update removed all existing shortcuts

### ISSUE THREAD

**Issue by rossapi** [onozaty/chrome-shortcutkey2url#22]
Hi 

the newest update on 10-30-2023 just removed all the history,  about over a 100 shortcuts are gone. how come? how could that happen? is there a way to restore it? 
it's simply reset back to the default 6 bookmarks including google, youtube and etc

**Comment by rossapi** [comment]
more update, even import again, it works for 5 mins. then disappears.  
I would wonder what's changed either extension code or google chrome

**Comment by rossapi** [comment]
I think the recent updates  since 5 days agao may have caused this issue.

**Comment by onozaty** [comment]
Hi @rossapi 

Sorry about that.
I have recently released a version that supports synchronization, and this seems to have affected it.

I will analyze the cause.
If it is possible, could you give us the imported files?

Thanks.

**Comment by rossapi** [comment]
HI @onozaty 
but below is an example with similar characters in the json file ( but not the actually original one, I didn't export the json for backup, so I have lost it due to this issue). 
it's been working fine since I started using it about 6 month back,  this morning it emptied chrome local storage all of a sudden, I do believe it's caused by update of storage logic.
I think there may be api issue if any logics related to empty storage or not ( reload or save or load with | empty logic). below is the example json data though if it's useful ( I obfuscated the data by the way , yet I don't think it's really about the data itself but about the api updates
[
  {
    "key": "Alerts",
    "hideOnPopup": false,
    "action": 3,
    "title": "alert test",
    "url": "http://alert.corporate.com/#/alerts",
    "script": ""
  },
  {
    "key": "search",
    "hideOnPopup": false,
    "action": 3,
    "title": "search by a list of contentids separated by comma ','",
    "url": "https://www.google.com/microervices/search.json?testToken=087426dbe2109f863d05da489&testKey=0HuFhpcEy0UzLZGG4PAm18GZuqIdl,12bAWwpPZyI501k9TSwFC,NfrMPPMpwrWqmlrKxewQMA&o=name,age&country=DE",
    "script": ""
  }
]

**Comment by rossapi** [comment]
in case this info is also useful, this is a corp laptop,  and Sync is disabled by your administrator" , so if the change is about storage local to storage sync, I guess it would cause issue , just a info

**Comment by onozaty** [comment]
> I would say if 1.6.0 has issues. do you think tags/1.5.1 is better? which version is the latest stable version? I can use it just unpack the extensions for now.

Could you please use 1.5.1?

The cause has been determined and is currently being corrected.
There is a limit to the maximum amount of space that can be saved in the case of synchronization, which seems to be the issue at this time.

**Comment by rossapi** [comment]
yes, I agree, and Chrome didn't suggest to use storage sync. but local only and it seems the storage sync is unstable and will gives away unexpected

so instead of saying we can support sync across browsers , I would suggest note it in next release that 
1. the best way is to use the plugin locally and add some details to where the json data is saved
2. should export and backup from time to time in case data is missing. 

but good to know you have found the reason. ! cool

**Comment by rossapi** [comment]
@onozaty thx for the quick update, got a plan to merge and public a new version?

**Comment by rossapi** [comment]
and another manifest version issue may also need to be consiered 
![image](https://github.com/onozaty/chrome-shortcutkey2url/assets/83838318/7dcc8633-be64-48ef-83ee-699b02270bb4)

**Comment by onozaty** [comment]
> @onozaty thx for the quick update, got a plan to merge and public a new version? I saw you published v1.6.1 should it be the one to use or the branch is still under dev&testing? thx

v1.6.1 is now available on the Chrome webstore.
Please update and use.

> and another manifest version issue may also need to be consiered ![image](https://user-images.githubusercontent.com/83838318/279862675-7dcc8633-be64-48ef-83ee-699b02270bb4.png)

If we change to manifest version 3, we will not be able to realize some of the functions, so we are keeping it at version 2.
Although a warning will appear, there is no problem in using it.

Thanks.

**Comment by AH-Hammi** [comment]
Sorry for that, I wasn't aware that this would be a possibility, that your organization could block the access to sync. Maybe it wasn't that good of an idea to just yeet out the old stored and just expect that the sync storage works.

**Comment by rossapi** [comment]
1. for the sync by org, I replied you in your proposal ticket, yes, it could happen for a lot of corp users. most admin won't allow sync data out of org, 
2. for the manifest version. I posted it up there ( instead of a new ticket) is because it looks to me if not resolved, as said by google official doc , support will be stopped . wonder if any new upgrade chrome won't work with any manifest v2 extensions. so to draw your attention

**Comment by onozaty** [comment]
Hi @rossapi 

> 2. for the manifest version. I posted it up there ( instead of a new ticket) is because it looks to me if not resolved, as said by google official doc , support will be stopped . wonder if any new upgrade chrome won't work with any manifest v2 extensions. so to draw your attention

I understand that v2 will not be available one day.
However, if i go to v3, there will be no way to execute the code specified in Script, so i plan to keep v2 until it is no longer available.

Thanks.

**Comment by rossapi** [comment]
thx for the update. I see the 1.6.1 is up to date in google extension publicly. we can for now close the issue. thx for quick response

**Comment by onozaty** [comment]
You contacted us immediately and I was able to respond to your request promptly.
Thank you very much.
