### ISSUE TITLE
Allow users to choose not to synchronize settings

### ISSUE THREAD

**Issue by onozaty** [onozaty/chrome-shortcutkey2url#25]
Since some users have expressed a desire to use different settings for each PC, we will allow users to choose not to synchronize in the settings.

**Comment by AH-Hammi** [comment]
Maybe rather create the option to store every shortcut at it's wished location, like a sync space, a local space and a managed space. So companies can install it by default and set some default always available shortcut's.

**Comment by onozaty** [comment]
> Maybe rather create the option to store every shortcut at it's wished location, like a sync space, a local space and a managed space. So companies can install it by default and set some default always available shortcut's.

At this time, add an option to disable synchronization as before.
I would like to consider doing more than that if users request it in the future, but I think implementing that would complicate things.

Thanks.

**Comment by AH-Hammi** [comment]
![image](https://github.com/onozaty/chrome-shortcutkey2url/assets/45588834/37e990f8-7922-4050-909b-53804804d363)
I was thinking about something like this, I will try to come up with the storage logic etc

**Comment by rossapi** [comment]
I think there are corp google account , the administrator can disable those syncs as well to sync 'out of to other places' , but I never didn't try that function myself in google admin console.

**Comment by AH-Hammi** [comment]
@rossapi Could you please tell what of the two ideas?

Another example how I think this could look
![image](https://github.com/onozaty/chrome-shortcutkey2url/assets/45588834/863763ed-fa04-4f1f-a287-33334e2d769a)

**Comment by onozaty** [comment]
Hi @AH-Hammi 

Sorry, in this Issue I would like to simply provide an option to make it work the same way as before.

There is no problem to consider it as a separate Issue, but we do not feel the need to go that far at this time, so it is unlikely that we will incorporate it even if we receive a Pull Request.
This is because incorporating a Pull Request in itself is costly in terms of testing, modifying the code, and maintenance.

I maintain the Firefox version the same way.

* https://github.com/onozaty/firefox-shortcutkey2url

Thanks.

**Comment by onozaty** [comment]
Released at v1.6.2

* https://github.com/onozaty/chrome-shortcutkey2url/releases/tag/v1.6.2
