### ISSUE TITLE
Make more room for shortcuts in sync space

### ISSUE THREAD

**Issue by AH-Hammi** [onozaty/chrome-shortcutkey2url#26]
By using multiple items to store the shortcuts it would be an option to sync more shortcuts.
The Limitation of Chrome is 8kb per item but 100kb sync storage.

**Comment by onozaty** [comment]
I considered this method, but decided against it because it would be too cumbersome to implement.
If a user has a large number of shortcut keys and insists on synchronization, it will be considered again.

Thanks.

**Comment by onozaty** [comment]
I found that registering the bookmarklet easily oversizes it, so I may have to address this in the near future.

**Comment by onozaty** [comment]
Released at v1.6.2

* https://github.com/onozaty/chrome-shortcutkey2url/releases/tag/v1.6.2
