### ISSUE TITLE
Make storage location individuals for every shortcut 

### ISSUE THREAD

**Issue by AH-Hammi** [onozaty/chrome-shortcutkey2url#29]
Create the ability to store every shortcut either in local storage or in sync storage. In case sync is not available warn the user in the front end and select local

**Comment by onozaty** [comment]
Thanks for the suggestion.
However, my view at this point is as follows. 

* https://github.com/onozaty/chrome-shortcutkey2url/issues/25#issuecomment-1791660663

> Sorry, in this Issue I would like to simply provide an option to make it work the same way as before.
> 
> There is no problem to consider it as a separate Issue, but we do not feel the need to go that far at this time, so it is unlikely that we will incorporate it even if we receive a Pull Request. This is because incorporating a Pull Request in itself is costly in terms of testing, modifying the code, and maintenance.
> 
> I maintain the Firefox version the same way.
> 
> * https://github.com/onozaty/firefox-shortcutkey2url
> 
> Thanks.
