### ISSUE TITLE
Startup speed 

### ISSUE THREAD

**Issue by meierjan** [onozaty/chrome-shortcutkey2url#9]
Hey, thank you for developing this plugin. It's really what I was looking for.

I wonder if it is possible to speed up the time that the plugin requires after hitting the str+. until it receives key events. Sometimes I am typing my shortcut too fast - so basically, before it can receive it / listens.

**Comment by onozaty** [comment]
Sorry for the late reply.

> Hey, thank you for developing this plugin. It's really what I was looking for.

Thank you 😄 

> I wonder if it is possible to speed up the time that the plugin requires after hitting the str+. until it receives key events. Sometimes I am typing my shortcut too fast - so basically, before it can receive it / listens.
> Since this extension receives events in the popup window, it cannot handle it if the input is made before the popup window is opened.

It is difficult to change this mechanism itself, but I will think about it once to see if there is any other way.

Thanks.

**Comment by onozaty** [comment]
> > I wonder if it is possible to speed up the time that the plugin requires after hitting the str+. until it receives key events. Sometimes I am typing my shortcut too fast - so basically, before it can receive it / listens.
> > Since this extension receives events in the popup window, it cannot handle it if the input is made before the popup window is opened.
> 
> It is difficult to change this mechanism itself, but I will think about it once to see if there is any other way.

So far, i have not found a good way to do this.
As an ongoing issue, I will leave this Issue unclosed.

**Comment by onozaty** [comment]
Hi @meierjan 

I share this just in case.
Someone was slow to respond due to not Pinning shortcutkey2url.

Are you pinned?

![shortcutkey2url-pin](https://user-images.githubusercontent.com/47337/170858163-927716da-bb6b-4336-9b84-0bee28e73b0d.gif)

Thanks.

**Comment by AH-Hammi** [comment]
For my part, I can't relate to this issue, pinning definitely helps, this issue can be closed
